MODEL:
  META_ARCHITECTURE: "RRPN"
  WEIGHT: "./models/IC-13-15-17-Trial-multiscale-picked-ft/model_0200000.pth"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvRRPNHead"

  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NMS: 0.3
    DETECTIONS_PER_IMG: 300

DATALOADER:
  SIZE_DIVISIBILITY: 1



