MODEL: 
  META_ARCHITECTURE: "RRPN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvRRPNHead"

  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128

DATASETS:
  TRAIN: ("RRPN_train", )
SOLVER:
  BASE_LR: 0.003
  WEIGHT_DECAY: 0.0001
  STEPS: (20000, 60000)
  MAX_ITER: 80000
  IMS_PER_BATCH: 1

