MODEL:
  META_ARCHITECTURE: "RRPN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    RPN_HEAD: "SingleConvRRPNHead"

  ROI_BOX_HEAD:
    NUM_CLASSES: 2
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256

DATASETS:
  TRAIN: ("RRPN_train", )
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, 100000)
  MAX_ITER: 150000
  IMS_PER_BATCH: 1

OUTPUT_DIR: './models/IC-13-15-Trial/'
